CREATE TABLE Personaje (
   id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   nombre VARCHAR(50) NOT NULL,
   pais VARCHAR(255) NOT NULL,
   imagenPersonaje MEDIUMBLOB NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
