CREATE TABLE Reflexion (
   id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   titulo VARCHAR(50) NOT NULL,
   contenido VARCHAR(255) NOT NULL,
   nivel_id INT,
   CONSTRAINT reflexion_nivel FOREIGN KEY (nivel_id) REFERENCES Nivel(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
